theme: jekyll-theme-minimal

title: Imputação de dados de NO2 do TROPOMI
logo: /assets/img/esquematico_projeto.png
description: Aplicação de modelos de Aprendizado de Máquina na estimação da coluna troposférica de NO2 do TROPOMI no estado do Pará
show_downloads: true
google_analytics:
github:
  zip_url: https://github.com/WesPereira/no2-data-imputation/archive/refs/heads/main.zip
  repository_url: https://github.com/WesPereira/no2-data-imputation
  datamap_url: https://datamap-webapp.vercel.app/
