title: Imputação de dados de NO2 do TROPOMI
logo: /assets/img/logo.png
description: Aplicação de modelos de Aprendizado de Máquina na estimação da coluna troposférica de NO2 do TROPOMI no estado do Pará
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

