theme: jekyll-theme-minimal

title: Aplicação de modelos de Aprendizado de Máquina na estimação da coluna troposférica de NO2 do TROPOMI no estado do Pará
logo:
description: Este projeto utiliza sensoriamento remoto e técnicas de Aprendizado de Máquina para estimar a concentração de NO2 na Amazônia, especificamente no Pará, Brasil. Envolve coleta e análise de dados de diversas fontes de sensoriamento remoto, mostrando resultados promissores e contribuindo para o monitoramento ambiental.
show_downloads: true
google_analytics:
github:
  zip_url: https://github.com/WesPereira/no2-data-imputation/archive/refs/heads/main.zip
  repository_url: https://github.com/WesPereira/no2-data-imputation
  datamap_url: https://datamap-webapp.vercel.app/
